In [3]:
import pandas as pd
import numpy as np


def forward(V, a, b, initial_distribution):
    alpha = np.zeros((V.shape[0], a.shape[0]))
    alpha[0, :] = initial_distribution * b[:, V[0]]

    for t in range(1, V.shape[0]):
        for j in range(a.shape[0]):
            # Matrix Computation Steps
            #                          ((1x2) . (1x2))              *     (1)
            #                        (1)            *     (1)
            alpha[t, j] = alpha[t - 1] @ a[:, j] * b[j, V[t]]

    return alpha


def backward(V, a, b):
    beta = np.zeros((V.shape[0], a.shape[0]))

    # setting beta(T) = 1
    beta[V.shape[0] - 1] = np.ones((a.shape[0]))

    # Loop in backward way from T-1 to
    # Due to python indexing the actual loop will be T-2 to 0
    for t in range(V.shape[0] - 2, -1, -1):
        for j in range(a.shape[0]):
            beta[t, j] = (beta[t + 1] * b[:, V[t + 1]]) @ a[j, :]

    return beta


def baum_welch(V, a, b, initial_distribution, n_iter=100):
    M = a.shape[0]
    T = len(V)

    for n in range(n_iter):
        alpha = forward(V, a, b, initial_distribution)
        beta = backward(V, a, b)

        xi = np.zeros((M, M, T - 1))
        for t in range(T - 1):
            denominator = alpha[t, :].T @ a * b[:, V[t + 1]].T @ beta[t + 1, :]
            for i in range(M):
                numerator = alpha[t, i] * a[i, :] * b[:, V[t + 1]].T * beta[t + 1, :].T
                xi[i, :, t] = numerator / denominator

        gamma = np.sum(xi, axis=1)
        a = np.sum(xi, 2) / np.sum(gamma, axis=1).reshape((-1, 1))

        # Add additional T'th element in gamma
        gamma = np.hstack((gamma, np.sum(xi[:, :, T - 2], axis=0).reshape((-1, 1))))

        K = b.shape[1]
        denominator = np.sum(gamma, axis=1)
        for l in range(K):
            b[:, l] = np.sum(gamma[:, V == l], axis=1)

        b = np.divide(b, denominator.reshape((-1, 1)))

    return {"a": a, "b": b}


# data = pd.read_csv("data_python.csv")

# V = data["Visible"].values

# Transition Probabilities
a = np.ones((2, 2))
a = a / np.sum(a, axis=1)

# Emission Probabilities
b = np.array(((1, 3, 5), (2, 4, 6)))
b = b / np.sum(b, axis=1).reshape((-1, 1))

# Equal Probabilities for the initial distribution
initial_distribution = np.array((0.5, 0.5))


In [8]:
transition_matrix = np.asarray([[0.5, 0.5], [0.3, 0.7]])
transition_matrix

array([[0.5, 0.5],
       [0.3, 0.7]])

In [9]:
emission_matrix = np.asarray([[0.3, 0.7], [0.8, 0.2]])
emission_matrix

array([[0.3, 0.7],
       [0.8, 0.2]])

In [11]:
initial_conditions = np.asarray([0.2, 0.8])[:, np.newaxis]
initial_conditions

array([[0.2],
       [0.8]])

In [14]:
observations = np.asarray(['N', 'N', 'N', 'N', 'N', 'E', 'E', 'N', 'N', 'N'])
observations

array(['N', 'N', 'N', 'N', 'N', 'E', 'E', 'N', 'N', 'N'], dtype='<U1')

In [23]:
observations_ind = [0 if o == 'N' else 1 for o in observations]
observations_ind

[0, 0, 0, 0, 0, 1, 1, 0, 0, 0]

In [74]:
n_time = len(observations)
n_states = 2
blah = np.zeros((n_time - 1, n_states, n_states))
for time_ind in range(n_time - 1):
    for state_ind1 in range(n_states):
        for state_ind2 in range(n_states):
            blah[time_ind, state_ind1, state_ind2] = (
                initial_conditions[state_ind1]
                * emission_matrix[state_ind1, observations_ind[time_ind]]
                * transition_matrix[state_ind1, state_ind2]
                * emission_matrix[state_ind2, observations_ind[time_ind + 1]]
            )
            




2.6874999999999996

In [83]:
state_ind1 = 0
state_ind2 = 1
time_ind = 4

np.sum(initial_conditions[:] * emission_matrix[:, observations_ind[time_ind]], axis=1)

array([0.22, 0.88])

In [65]:
blah.sum(axis=0) / blah.sum(axis=1, keepdims=True).sum(axis=0).T

array([[0.21545319, 0.3268945 ],
       [0.20528771, 0.91446345]])

In [70]:
blah.sum(axis=0)

array([[0.145, 0.22 ],
       [0.528, 2.352]])

array([0.673, 2.572])